---
# DESCRIPTION: Github actions config
# This name is key to badges in README.rst, so we use the name build
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

name: static-power-analysis-flow

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CI_OS_NAME: linux
  CI_COMMIT: ${{ github.sha }}
  CCACHE_COMPRESS: 1
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_LIMIT_MULTIPLE: 0.95
  INSTALL_DIR: ${{ github.workspace }}/install
  RELOC_DIR: ${{ github.workspace }}/relloc

defaults:
  run:
    shell: bash
    working-directory: repo

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  flow:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    name: Build | ${{ matrix.os }}
    env:
      CI_BUILD_STAGE_NAME: build
      CI_RUNS_ON: ${{ matrix.os }}
      CACHE_BASE_KEY: build-${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-11 gcc make flex bison help2man perl python3 libfl2 libfl-dev zlib1g zlib1g-dev ccache mold libgoogle-perftools-dev numactl tcl swig cmake libeigen3-dev

      - name: Fetch Verilator
        run: git clone https://github.com/antmicro/verilator -b "saif"

      - name: Build Verilator
        run: |
          cd verilator
          autoconf
          ./configure --prefix $(pwd)
          make -j $(nproc)
          export PATH=$PATH:$(pwd)/bin/
          cd ..

      - name: Fetch OpenSTA
        run: git clone https://github.com/The-OpenROAD-Project/OpenSTA

      - name: Build OpenSTA
        run: |
          cd OpenSTA
          cd ..

      - name: Fetch OpenROAD-flow-scripts
        run: git clone https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts

      - name: Build OpenROAD-flow-scripts
        run: |
          cd OpenROAD-flow-scripts
          cd ..

      - name: Show contents
        run: ls